version: 2

project_name: up

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: up
    main: ./main.go
    binary: up
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: up
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md

checksum:
  name_template: 'checksums-up.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: uplang
    name: tools
  draft: false
  prerelease: auto
  mode: keep-existing
  name_template: "Tool: up v{{.Version}}"

brews:
  - name: up
    repository:
      owner: uplang
      name: brew
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/uplang/tools
    description: "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
    license: GPL-3.0
    skip_upload: auto
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    caveats: |
      UP CLI has been installed!

      Documentation: https://github.com/uplang/tools/tree/main/up

      Common commands:
        up parse -i config.up --pretty
        up format -i config.up
        up validate -i config.up
