version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: up
    main: ./main.go
    binary: up
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: up
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: uplang
    name: tools
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}/up v{{.Version}}"

brews:
  - repository:
      owner: uplang
      name: homebrew-tap
    folder: Formula
    homepage: https://uplang.org
    description: UP (Unified Properties) CLI tool
    license: GPL-3.0
    test: |
      system "#{bin}/up --version"
    install: |
      bin.install "up"

